In [1]:
import numpy as np

In [72]:
a = np.random.randint(1,101,100).reshape(10,10)

In [73]:
a

array([[42, 37,  8, 40, 57, 92, 61,  6, 34,  6],
       [91, 19, 85, 81, 68, 26,  5,  1, 32, 78],
       [16, 66, 65, 33, 20,  5, 21, 57, 52, 57],
       [ 4,  9, 67, 45, 56, 69, 28, 23, 20, 61],
       [68, 94, 67, 12, 74, 38, 70, 93,  4, 80],
       [89, 42, 41, 71, 61, 28, 98, 51, 90, 21],
       [31, 65, 48, 37, 72, 65, 24, 36, 71,  6],
       [50, 88, 64, 41, 68, 35, 97, 25, 66, 30],
       [89, 73, 10, 30, 50, 69, 82, 76, 86, 77],
       [38, 35, 75, 84, 85, 59, 35, 29, 49, 32]])

In [10]:
a[::2].mean(axis =1)

array([40.7, 52.9, 52.4, 53. , 54. ])

In [11]:
a[:,1::2].std(axis =0)

array([28.2       , 26.91913817, 25.69221672, 25.16127978, 23.92153841])

In [14]:
np.sum(np.count_nonzero(a<5, axis =1)>0)

4

In [38]:
sum(np.apply_along_axis(lambda x: np.any(x<5), axis =1 , arr = a))

2

In [34]:
np.where(np.any(a>90, axis = 0))

(array([0, 1, 3, 4, 5, 6, 7]),)

In [37]:
sum(np.any(a<5, axis=1))

2

In [39]:
value , count = np.unique(a, return_counts = True)

In [47]:
(value[count>1])

array([  7,  20,  23,  29,  30,  31,  33,  35,  39,  41,  43,  53,  55,
        62,  66,  72,  77,  78,  81,  87,  93,  96,  99, 100])

In [48]:
np.unique(a)

array([  2,   4,   6,   7,   9,  10,  13,  15,  16,  18,  19,  20,  21,
        22,  23,  24,  26,  28,  29,  30,  31,  32,  33,  34,  35,  36,
        37,  39,  41,  43,  46,  47,  48,  49,  50,  53,  55,  56,  57,
        60,  61,  62,  64,  65,  66,  67,  69,  70,  71,  72,  73,  77,
        78,  79,  80,  81,  82,  84,  85,  86,  87,  89,  90,  92,  93,
        96,  99, 100])

In [50]:
sum(np.apply_along_axis(lambda x: len(np.unique(x)) != len(x), axis =1 ,arr = a))

4

In [58]:
np.any(np.apply_along_axis(lambda x: np.unique(x, return_counts = True)[1]>1 , axis=1, arr = a),axis =1)

ValueError: could not broadcast input array from shape (9,) into shape (10,)

In [66]:
def carr(n,m):
    
    arr = np.zeros(shape= (n,m))
    arr[:,-1] = 1
    arr[:,:1] = 1
    arr[0,:] = 1
    arr[ -1, :] = 1
    
    return arr

In [68]:
carr(5,5)

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [69]:
def closest(arr, v):
    a = np.array(arr)
    b = abs(a-v)
    idx = b.argmin()
    
    return arr[idx]

In [70]:
a = [10, 3, 7, 8 , 15] 

In [71]:
closest(a,4)

3

In [75]:
np.count_nonzero(np.any(a<5, axis=1))

3

In [79]:
np.where(np.any(a>90, axis = 0))[0]

array([0, 1, 5, 6, 7])

In [80]:
val, count = np.unique(a, return_counts = True)

In [81]:
val[count>1]

array([ 4,  5,  6, 20, 21, 28, 30, 32, 35, 37, 38, 41, 42, 50, 57, 61, 65,
       66, 67, 68, 69, 71, 85, 89])

In [86]:

a = np.array([[1, 2, 8], [3, 4, 1], [10, 5, 5]])

In [91]:
np.where(np.any(a>7, axis= 0))

array([1, 3])

In [92]:
a = np.array([[-1, 2, 1], [1, 4, 5]])

In [93]:
a

array([[-1,  2,  1],
       [ 1,  4,  5]])

In [94]:
idx = np.where(np.any(a<0, axis=1))[0]

In [95]:
idx

array([0])

In [97]:
a[idx] =np.zeros(a.shape[1])

In [98]:
a

array([[0, 0, 0],
       [1, 4, 5]])

In [99]:
a.shape

(2, 3)

In [100]:
a.shape[1]

3

In [101]:
a.shape[0]

2

In [102]:
np.zeros(2)

array([0., 0.])

In [103]:
np.zeros(3)

array([0., 0., 0.])

In [107]:
a = np.array([[1, 2, 1], [1, 4, 5]])
a

array([[1, 2, 1],
       [1, 4, 5]])

In [111]:
b = np.sum(a, axis=1).reshape(2,1)

In [112]:
a/b

array([[0.25, 0.5 , 0.25],
       [0.1 , 0.4 , 0.5 ]])

In [114]:
a = np.array([3, 2, 7, 11, 8, 5, 10, 14])

In [115]:
b = a[:-1]
b

array([ 3,  2,  7, 11,  8,  5, 10])

In [117]:
c= a[1:]
c

array([ 2,  7, 11,  8,  5, 10, 14])

In [130]:
b[(b%2==0) & (c%2==1)]

array([2, 8])

In [129]:
A = np.array([3, 2, 7, 11, 8, 5, 10, 14])

B = A[:-1]
C = A[1:]
B[(B % 2 == 0) & (C % 2 == 1)]

array([2, 8])

In [121]:
c%2 ==1

array([False,  True,  True, False,  True, False, False])

In [132]:
a = np.array([5, 8, 3, 1, 10, 9, 12])

In [133]:
b = a[1:-1]

In [134]:
b

array([ 8,  3,  1, 10,  9])

In [135]:
b>a[:-2]

array([ True, False, False,  True, False])

In [136]:
b>a[2:]

array([ True,  True, False,  True, False])

In [138]:
b[(b>a[:-2])&(b>a[2:])]

array([ 8, 10])

In [141]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 8, 8]])

In [149]:
np.count_nonzero(np.apply_along_axis(lambda x: len(np.unique(x))!= len(x), axis=1, arr=a))

2

In [150]:
np.sort(a,axis=1)

array([[1, 2, 3],
       [1, 1, 1],
       [2, 8, 8]])

In [151]:
a

array([[1, 2, 3],
       [1, 1, 1],
       [2, 8, 8]])

In [152]:
np.count_nonzero(np.any(a[:, 1:] == a[:,:-1], axis =1))

2

In [184]:
a = np.array([
    [9, 12, 3, 7, 12],
    [3, 10, 2, 6, 4],
    [18, 24, 6, 17, 11],
    [15, 21, 8, 13, 12],
    [1, 18, 4, 22, 15]
])

In [185]:
row_min = np.argmin(a, axis=1)
col_max = np.argmax(a, axis=0)

In [186]:
col_max

array([2, 2, 3, 4, 4])

In [187]:
row_min

array([2, 2, 2, 2, 0])

In [193]:
np.where(col_max[row_min] == np.arange(a.shape[0]))[0]

array([3])

In [190]:
np.arange(a.shape[0])

array([0, 1, 2, 3, 4])

In [182]:
row_max[row_max == col_min]

array([10])

In [183]:
col_min[row_max == col_min]

array([10])

In [194]:
row = np.argmin(a, axis =1)
col = np.argmax(a, axis =0)

In [207]:
s_row = np.where(col[row] == np.arange(a.shape[0]))[0]

In [208]:
s_col=col[s_row]

In [226]:
a = np.array([
    [2, 16, 13, 3],
    [11, 5, 8, 10],
    [7, 9, 12, 6],
    [14, 4, 1, 15]
])

In [217]:
magic_num = a[0].sum()
magic_num

34

In [216]:
np.all(np.sum(a,axis=1)==magic_num)

True

In [215]:
np.all(np.sum(a,axis=0)==magic_num)

True

In [218]:
np.sum(np.diag(a)) == magic_num

True

In [220]:
np.sum(np.diag(np.fliplr(a))) == magic_num

True

In [229]:
def magic(arr):
    
    magic_num = arr[0].sum()
    
    if (np.all(np.sum(arr,axis=1)==magic_num)) & (np.all(np.sum(arr,axis=0)==magic_num)) & (np.sum(np.diag(arr)) == magic_num) & (np.sum(np.diag(np.fliplr(arr))) == magic_num):
        return True
    else: 
        return False

In [230]:
magic(a)

True