## Answer for question 1(a-g)

In [1]:
import numpy as np

In [2]:
q1 = np.random.randint(1,101,100).reshape(10,-1)

In [3]:
print(q1)

[[ 78  94  23  68  99  76  11  48  77  98]
 [ 18   8  74  54   3  21  59  85  46  49]
 [ 64  49  11  25  75  52   6  94  80  64]
 [ 96  28  89  25  58  12  57  99  16  19]
 [ 85  20  30  30  72  33  98  41  73  40]
 [  5  95  91  85  30  85  43   9  28  71]
 [ 33  22  55  51  19   4  39  77  61   4]
 [ 89  94  18  60  43  75  56  52  84  65]
 [ 80  16  17  25  27 100  73  63  95  38]
 [ 59  37  13  52  47  73  32  31  66  76]]


Answer 1_(a)

In [6]:
#Answer for Quiz1_a: The minimum and maximum values in the array
minimum = q1.min()
maximum = q1.max()
print(f"Answer for Question 1_a :")
print(f"The minimum value: {minimum}")
print(f"The maximum value: {maximum}")

Answer for Question 1_a :
The minimum value: 1
The maximum value: 100


Answer 1_(b)

In [7]:
#Answer for Quiz1_b: The average of every even row(row 0, 2 ,...8)
answer_b = q1[::2].mean(axis=1)
print(f"Answer for Question 1_b : {answer_b}")

Answer for Question 1_b : [42.3 43.1 46.9 49.1 50.3]


Answer 1_(c)

In [8]:
#Answer for Quiz1_c: The standard of deviation in every odd columnn
answer_c = q1[:,1::2].std(axis=0)
print(f"Answer for Question 1_c : {answer_c}")

Answer for Question 1_c : [26.8931218  26.80223871 30.94123462 22.84381754 27.67598237]


Answer 1_(d)

In [9]:
#Answer for Quiz1_d: How many rows contain a number less than 5?
row_less5 = np.any(q1<5, axis=1)
answer_d = sum(row_less5)
print(f"Answer for Question 1_d : {answer_d}")

Answer for Question 1_d : 7


Answer 1_(e)

In [10]:
#Answer for Quiz_e: Which column contain a number greater than 90? (print the index of the column)
colum_90 = np.any(q1 > 90, axis = 0)
index_90 = np.where(colum_90)[0]
print(f"Answer for Question 1_e : {index_90}")

Answer for Question 1_e : [1 2 5]


Answer 1_(f)

In [11]:
#Answer for Quiz_f: which numbers appear in the matrix more than twice?
values, counts = np.unique(q1, return_counts = True)
num_2 = values[counts > 2]

if len(num_2)>0:
    print(f"Answer for Question 1_f : {num_2}")
else:
    print(f"Answer for Question 1_f : None")


Answer for Question 1_f : [ 2  4  8 43 46 47 48 71 72 75 84 86]


Answer 1_(g)

In [5]:
#Answer for Quiz_g: How many row contains duplicate value?
row_duplicate = np.sum(np.apply_along_axis(lambda x :len(np.unique(x))!= len(x), axis = 1, arr = q1 ))

print(f"Answer for Question 1_g: {row_duplicate}")

Answer for Question 1_g: 4
