In [2]:
import numpy as np

Answer for Question 2: Write a function that creates an array with shape (n,m) that is all zeros except for the border


In [10]:
def array_border(n, m):
    arr = np.zeros((n, m), dtype = int)
    
    arr[0, :] = 1
    arr[-1, :] = 1
    arr[:, 0] = 1
    arr[:, -1] = 1
    
    return arr

In [11]:
a = array_border(6, 5)
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
