In [1]:
import numpy as np

In [2]:
A = np.array([[4,2,1], [3,1,5], [2,1,3]])
b = np.array([10,6,7]).reshape(-1,1)

In [5]:
A

array([[4, 2, 1],
       [3, 1, 5],
       [2, 1, 3]])

In [6]:
b

array([[10],
       [ 6],
       [ 7]])

The answer for Question 7_a

In [7]:
answer_a = np.linalg.det(A)

In [8]:
answer_a

-5.000000000000001

In [11]:
print(f"The answer for Question 7_a is :{answer_a}")

The answer for Question 7_a is :-5.000000000000001


The answer for Question 7_b

In [12]:
answer_b = np.linalg.inv(A)

In [13]:
answer_b

array([[ 0.4,  1. , -1.8],
       [-0.2, -2. ,  3.4],
       [-0.2,  0. ,  0.4]])

In [31]:
def M_inverse(arr):
    print("The answer for Question 7_b is:")
    try: 
        inv = np.linalg.inv(arr)
        print(f"There is invertible. \nAnd it is \n{np.linalg.inv(arr)}")
    except np.linalg.LinAlgError:
        print("There is no invertible")

In [33]:
M_inverse(A)

The answer for Question 7_b is:
There is invertible. 
And it is 
[[ 0.4  1.  -1.8]
 [-0.2 -2.   3.4]
 [-0.2  0.   0.4]]


The answer for Question 7_c

Since A inverible matrix exist, We apply the inverse matrix to both sides to solve for x.

In [34]:
x = np.linalg.inv(A) @ b

In [35]:
x

array([[-2.6],
       [ 9.8],
       [ 0.8]])

In [37]:
print(f"The answer for question 7_c is :\n {x}")

The answer for question 7_c is :
 [[-2.6]
 [ 9.8]
 [ 0.8]]


The answer for Quenstion 7_d

In [38]:
eigenvalues, eigenvectors = np.linalg.eig(A)

In [39]:
eigenvalues

array([ 7.04804585,  1.44343285, -0.4914787 ])

In [41]:
eigenvectors

array([[ 0.58800699,  0.65315053,  0.40044041],
       [ 0.66832949, -0.61183564, -0.91573217],
       [ 0.45561329, -0.44615192,  0.03289476]])

In [43]:
print(f"The answer for question 7_d is : \n eigenvalues: {eigenvalues} \n eigenvectors:\n {eigenvectors}")

The answer for question 7_d is : 
 eigenvalues: [ 7.04804585  1.44343285 -0.4914787 ] 
 eigenvectors:
 [[ 0.58800699  0.65315053  0.40044041]
 [ 0.66832949 -0.61183564 -0.91573217]
 [ 0.45561329 -0.44615192  0.03289476]]


The answer for question 7_e

In [50]:
A @ eigenvectors

array([[ 4.14430024,  0.94277893, -0.19680793],
       [ 4.7104169 , -0.88314365,  0.45006286],
       [ 3.21118334, -0.64399034, -0.01616707]])

In [54]:
eigenvalues = np.diag(eigenvalues)

In [63]:
eigenvalues

array([[ 7.04804585,  0.        ,  0.        ],
       [ 0.        ,  1.44343285,  0.        ],
       [ 0.        ,  0.        , -0.4914787 ]])

In [70]:
left = A @eigenvectors
left

array([[ 4.14430024,  0.94277893, -0.19680793],
       [ 4.7104169 , -0.88314365,  0.45006286],
       [ 3.21118334, -0.64399034, -0.01616707]])

In [71]:
right = eigenvectors @ eigenvalues 
right

array([[ 4.14430024,  0.94277893, -0.19680793],
       [ 4.7104169 , -0.88314365,  0.45006286],
       [ 3.21118334, -0.64399034, -0.01616707]])

In [73]:
np.all(np.isclose(left,right))

True

In [78]:
print("A * V : \n", left)
print("V * Lambda: \n",right)
print(f"The answer for question 7_e is : [A * V = V * Lambda] is {np.all(np.isclose(left,right))}")

A * V : 
 [[ 4.14430024  0.94277893 -0.19680793]
 [ 4.7104169  -0.88314365  0.45006286]
 [ 3.21118334 -0.64399034 -0.01616707]]
V * Lambda: 
 [[ 4.14430024  0.94277893 -0.19680793]
 [ 4.7104169  -0.88314365  0.45006286]
 [ 3.21118334 -0.64399034 -0.01616707]]
The answer for question 7_e is : [A * V = V * Lambda] is True
